package com.cooksys.models;

// Generated Sep 24, 2014 11:11:27 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TTweets generated by hbm2java
 */
public class TTweets implements java.io.Serializable {

	private Integer idtTweets;
	private TUsers TUsers;
	private String tweet;
	private String userNick;
	private Date timeStamp;

	public TTweets() {
	}

	public TTweets(TUsers TUsers, String tweet, String userNick, Date timeStamp) {
		this.TUsers = TUsers;
		this.tweet = tweet;
		this.userNick = userNick;
		this.timeStamp = timeStamp;
	}

	public Integer getIdtTweets() {
		return this.idtTweets;
	}

	public void setIdtTweets(Integer idtTweets) {
		this.idtTweets = idtTweets;
	}

	public TUsers getTUsers() {
		return this.TUsers;
	}

	public void setTUsers(TUsers TUsers) {
		this.TUsers = TUsers;
	}

	public String getTweet() {
		return this.tweet;
	}

	public void setTweet(String tweet) {
		this.tweet = tweet;
	}

	public String getUserNick() {
		return this.userNick;
	}

	public void setUserNick(String userNick) {
		this.userNick = userNick;
	}

	public Date getTimeStamp() {
		return this.timeStamp;
	}

	public void setTimeStamp(Date timeStamp) {
		this.timeStamp = timeStamp;
	}

}
