package com.cooksys.models;

// Generated Sep 24, 2014 11:11:27 AM by Hibernate Tools 3.4.0.CR1

/**
 * TFollowing generated by hbm2java
 */
public class TFollowing implements java.io.Serializable {

	private Integer idtFollowing;
	private TUsers TUsers;
	private String userName;
	private String userFollowing;

	public TFollowing() {
	}

	public TFollowing(TUsers TUsers, String userName, String userFollowing) {
		this.TUsers = TUsers;
		this.userName = userName;
		this.userFollowing = userFollowing;
	}

	public Integer getIdtFollowing() {
		return this.idtFollowing;
	}

	public void setIdtFollowing(Integer idtFollowing) {
		this.idtFollowing = idtFollowing;
	}

	public TUsers getTUsers() {
		return this.TUsers;
	}

	public void setTUsers(TUsers TUsers) {
		this.TUsers = TUsers;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserFollowing() {
		return this.userFollowing;
	}

	public void setUserFollowing(String userFollowing) {
		this.userFollowing = userFollowing;
	}

}
