package com.cooksys.models;

// Generated Sep 24, 2014 11:11:27 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TUsers generated by hbm2java
 */
public class TUsers implements java.io.Serializable {

	private Integer userId;
	private String userName;
	private String userPw;
	private String userRole;
	private String userNickname;
	private Set TFollowings = new HashSet(0);
	private Set TTweetses = new HashSet(0);

	public TUsers() {
	}

	public TUsers(String userName, String userPw, String userRole,
			String userNickname) {
		this.userName = userName;
		this.userPw = userPw;
		this.userRole = userRole;
		this.userNickname = userNickname;
	}

	public TUsers(String userName, String userPw, String userRole,
			String userNickname, Set TFollowings, Set TTweetses) {
		this.userName = userName;
		this.userPw = userPw;
		this.userRole = userRole;
		this.userNickname = userNickname;
		this.TFollowings = TFollowings;
		this.TTweetses = TTweetses;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserPw() {
		return this.userPw;
	}

	public void setUserPw(String userPw) {
		this.userPw = userPw;
	}

	public String getUserRole() {
		return this.userRole;
	}

	public void setUserRole(String userRole) {
		this.userRole = userRole;
	}

	public String getUserNickname() {
		return this.userNickname;
	}

	public void setUserNickname(String userNickname) {
		this.userNickname = userNickname;
	}

	public Set getTFollowings() {
		return this.TFollowings;
	}

	public void setTFollowings(Set TFollowings) {
		this.TFollowings = TFollowings;
	}

	public Set getTTweetses() {
		return this.TTweetses;
	}

	public void setTTweetses(Set TTweetses) {
		this.TTweetses = TTweetses;
	}

}
